const RESOURCE_LINKS: Record<string, string> = {
  "MDN": "https://developer.mozilla.org/en-US/docs/Web",
  "freeCodeCamp": "https://www.freecodecamp.org/learn/",
  "A11y Project": "https://www.a11yproject.com/checklist/",
  "JavaScript.info": "https://javascript.info/",
  "Frontend Masters": "https://frontendmasters.com/learn/",
  "React Docs": "https://react.dev/learn",
  "TypeScript Handbook": "https://www.typescriptlang.org/docs/handbook/intro.html",
  "Vite Docs": "https://vite.dev/guide/",
  "Vitest": "https://vitest.dev/guide/",
  "Vercel": "https://vercel.com/docs",
  "Python Docs": "https://docs.python.org/3/",
  "Node Docs": "https://nodejs.org/docs/latest/api/",
  "FastAPI Docs": "https://fastapi.tiangolo.com/",
  "Postman": "https://learning.postman.com/docs/",
  "MongoDB University": "https://learn.mongodb.com/",
  "SQLBolt": "https://sqlbolt.com/",
  "Docker Docs": "https://docs.docker.com/",
  "Render": "https://render.com/docs",
  "Railway": "https://docs.railway.com/",
  "Tailwind Docs": "https://tailwindcss.com/docs",
  "TanStack Query": "https://tanstack.com/query/latest/docs/framework/react/overview",
  "System Design Primer": "https://github.com/donnemartin/system-design-primer",
  "Playwright": "https://playwright.dev/docs/intro",
  "GitHub Actions": "https://docs.github.com/en/actions",
  "Kaggle Learn": "https://www.kaggle.com/learn",
  "Pandas Docs": "https://pandas.pydata.org/docs/",
  "Power BI Learn": "https://learn.microsoft.com/en-us/training/powerplatform/power-bi/",
  "Tableau Public": "https://public.tableau.com/app/learn/how-to-videos",
  "Scikit-learn Docs": "https://scikit-learn.org/stable/user_guide.html",
  "Andrew Ng ML": "https://www.coursera.org/specializations/machine-learning-introduction",
  "GitHub": "https://docs.github.com/",
  "Medium": "https://help.medium.com/hc/en-us",
  "StatQuest": "https://statquest.org/video-index/",
  "Kaggle": "https://www.kaggle.com/docs",
  "Papers with Code": "https://paperswithcode.com/",
  "PyTorch Tutorials": "https://docs.pytorch.org/tutorials/",
  "TensorFlow Guides": "https://www.tensorflow.org/guide",
  "Hugging Face Course": "https://huggingface.co/learn/llm-course/chapter1/1",
  "AWS Skill Builder": "https://skillbuilder.aws/",
  "Linux Journey": "https://linuxjourney.com/",
  "DigitalOcean Guides": "https://www.digitalocean.com/community/tutorials",
  "Play with Docker": "https://labs.play-with-docker.com/",
  "Terraform Learn": "https://developer.hashicorp.com/terraform/tutorials",
  "Ansible Docs": "https://docs.ansible.com/",
};

export function getResourceUrl(resource: string) {
  return RESOURCE_LINKS[resource] || `https://www.google.com/search?q=${encodeURIComponent(`${resource} official documentation`)}`;
}
